---
title: "13 - The syntax of events"
output:
  html_document:
    css: webex.css
    includes:
      after_body: webex.js
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!requireNamespace("webex")) {
  stop("You must have the 'webex' package installed to knit HTML from this template.\n   devtools::install_github(\"dalejbarr/webex\")")
} else {
  library("webex")
}
```

# Label the tense and aspect of the following sentences

(NB the "future" tense should have inverted commas round it, but the software does not allow me to do this!)

1. They won't have started the exam yet. TENSE: `r mcq(c("Present", "Past", answer = "Future", "NONE"))` ASPECT: `r mcq(c("simple", answer = "perfect", "progressive", "perfect progressive"))`

2. He was being deliberately obtuse. TENSE: `r mcq(c("Present", answer = "Past", "Future", "NONE"))` ASPECT: `r mcq(c("simple", "perfect", answer = "progressive", "perfect progressive"))`

3. Jack had been having a very good time in Mallorca. TENSE: `r mcq(c("Present", answer = "Past","Future", "NONE"))` ASPECT: `r mcq(c("simple", "perfect", "progressive", answer = "perfect progressive"))`

4. Jen is really open to new experiences. TENSE: `r mcq(c(answer = "Present", "Past", "Future", "NONE"))` ASPECT: `r mcq(c(answer = "simple", "perfect", "progressive", "perfect progressive"))`

5. What a messy kitchen! Charles must have been here. TENSE: `r mcq(c("Present", "Past", "Future", answer = "NONE"))` ASPECT: `r mcq(c("simple", answer = "perfect", "progressive", "perfect progressive"))`

6. Sandra won't be living here next year. TENSE: `r mcq(c("Present", "Past", answer = "Future", "NONE"))` ASPECT: `r mcq(c("simple", "perfect", answer = "progressive", "perfect progressive"))`

7. Have you eaten that cheese yet? TENSE: `r mcq(c(answer = "Present", "Past", "Future", "NONE"))` ASPECT: `r mcq(c("simple", answer = "perfect", "progressive", "perfect progressive"))`

8. You shouldn't be studying so hard. TENSE: `r mcq(c("Present", "Past", "Future", answer = "NONE"))` ASPECT: `r mcq(c("simple", "perfect", answer = "progressive", "perfect progressive"))`

9. Carlos is practising his violin a lot these days. TENSE: `r mcq(c(answer = "Present", "Past", answer = "Future", "NONE"))` ASPECT: `r mcq(c("simple", "perfect", answer = "progressive", "perfect progressive"))`

10. Clarice hadn't been paying attention at the time of the accident. TENSE: `r mcq(c("Present", answer = "Past", "Future", "NONE"))` ASPECT: `r mcq(c("simple", "perfect", "progressive", answer = "perfect progressive"))`






`r hide("Answers")`

1. They won't have started the exam yet. FUTURE PERFECT.

2. He was being deliberately obtuse. PAST PROGRESSIVE

3. Jack had been having a very good time in Mallorca. PAST PERFECT PROGRESSIVE

4. Jen is really open to new experiences. PRESENT SIMPLE

5. What a messy kitchen! Charles must have been here. PERFECTIVE ASPECT ONLY (NO TENSE ON 'HAVE')

6. Sandra won't be living here next year. FUTURE PROGRESSIVE

7. Have you eaten that cheese yet? PRESENT PERFECT

8. You shouldn't be studying so hard. PROGRESSIVE ASPECT ONLY (NO TENSE ON 'BE')

9. Carlos is practising his violin a lot these days. PRESENT PROGRESSIVE

10. Clarice hadn't been paying attention at the time of the accident. PAST PERFECT PROGRESSIVE.

`r unhide()`

