---
title: "16 - Mood, modality and voice"
output:
  html_document:
    css: webex.css
    includes:
      after_body: webex.js
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!requireNamespace("webex")) {
  stop("You must have the 'webex' package installed to knit HTML from this template.\n   devtools::install_github(\"dalejbarr/webex\")")
} else {
  library("webex")
}
```

## Fill the gaps

The term "Mood" refers to a speaker's att`r fitb("itude")` towards the sentence they are producing. There are four main types of mood; de`r fitb("clarative")`, im`r fitb("perative")`, in`r fitb("terrogative")`, and ex`r fitb("clamative")`. The term "modality" relates to the two concepts; ob`r fitb("ligation")` (or `r fitb("deontic")` modality), and poss`r fitb("ibility")` (or `r fitb("epistemic")` modality). It is generally regarded as a subcomponent of "mood". Voice refers to the devices used by a language to fore`r fitb("ground")` or top`r fitb("icalise")` particular arguments. English has an active voice (Subject is the topic) and  `r fitb("passive")` voice (non-subject is promoted to topic position). Some linguists have also identified a "middle" voice.

## What is wrong with the following sentences?

1. What he was doing? `r mcq(c(answer = "Failure to invert auxiliary verb in non-subject question", "Failure to invert copula in yes-no question", "Wh-movement without deletion of moved constituent", "Failure to invert auxiliary in exclamative", "Incorrect application of do-support in a subject question", "Failure to omit subject in imperative"))`
2. Who did eat eat all the pies? `r mcq(c("Failure to invert auxiliary verb in non-subject question", "Failure to invert copula in yes-no question", "Wh-movement without deletion of moved constituent", "Failure to invert auxiliary in exclamative", answer = "Incorrect application of do-support in a subject question", "Failure to omit subject in imperative"))`
3. Boy we're having a good time!! `r mcq(c("Failure to invert auxiliary verb in non-subject question", "Failure to invert copula in yes-no question", "Wh-movement without deletion of moved constituent", answer = "Failure to invert auxiliary in exclamative", "Incorrect application of do-support in a subject question", "Failure to omit subject in imperative"))`
4. He's happy? `r mcq(c("Failure to invert auxiliary verb in non-subject question", answer = "Failure to invert copula in yes-no question", "Wh-movement without deletion of moved constituent", "Failure to invert auxiliary in exclamative", "Incorrect application of do-support in a subject question", "Failure to omit subject in imperative"))`
5. Who did he give the book to someone? `r mcq(c("Failure to invert auxiliary verb in non-subject question", "Failure to invert copula in yes-no question", answer = "Wh-movement without deletion of moved constituent", "Failure to invert auxiliary in exclamative", "Incorrect application of do-support in a subject question", "Failure to omit subject in imperative"))`
6. You put that bottle of paint down! `r mcq(c("Failure to invert auxiliary verb in non-subject question", "Failure to invert copula in yes-no question", "Wh-movement without deletion of moved constituent", "Failure to invert auxiliary in exclamative", "Incorrect application of do-support in a subject question", answer = "Failure to omit subject in imperative"))`
7. How many cakes he has eaten? `r mcq(c(answer = "Failure to invert auxiliary verb in non-subject question", "Failure to invert copula in yes-no question", "Wh-movement without deletion of moved constituent", "Failure to invert auxiliary in exclamative", "Incorrect application of do-support in a subject question", "Failure to omit subject in imperative"))`

## Do the following modal verbs express deontic or epistemic modality?

1. You must be joking! `r mcq(c("Deontic", answer = "Epistemic"))`
2. Q: Does anyone know a late bar? A: The King George ought to be open. `r mcq(c("Deontic", answer = "Epistemic"))`
3. You can't have dinner at this establishment unless you are wearing a tie. `r mcq(c(answer = "Deontic", "Epistemic"))`
4. The train to York shouldn't be long now. `r mcq(c("Deontic", answer = "Epistemic"))`
5. You'll have to work hard if you want to be successful. `r mcq(c(answer = "Deontic", "Epistemic"))`

# Are the following sentences active or passive? Use the "hedgehogs" test to find out!

1. She's been really unlucky recently! `r mcq(c(answer = "Active", "Passive"))`
2. They've just been badly criticised.`r mcq(c("Active", answer = "Passive"))`
3. The car needs to be mended. `r mcq(c("Active", answer = "Passive"))`
4. I have had enough of your glib comments! `r mcq(c(answer = "Active", "Passive"))`
5. By the time we arrive all the food will have been eaten. `r mcq(c("Active", answer = "Passive"))`
6. She's tried, on numerous occasions, to contact her bank manager. `r mcq(c(answer = "Active", "Passive"))`
7. Hopefully, we'll be successful in the next round. `r mcq(c(answer = "Active", "Passive"))`
8. When we arrived, the house was being demolished. `r mcq(c("Active", answer = "Passive"))`


`r hide("Click for answers")`

# Fill the gaps

The term "Mood" refers to a speaker's ATTITUDE towards the sentence they are producing. There are four main types of mood; DECLARATIVE, IMPERATIVE, INTERROGATIVE, and EXCLAMATIVE. The term "modality" relates to the two concepts; OBLIGATION (or DEONTIC modality), and POSSIBILITY (or EPISTEMIC modality). It is generally regarded as a subcomponent of "mood". Voice refers to the devices used by a language to FOREGROUND or TOPICALISE particular arguments. English has an active voice (Subject is the topic) and  PASSIVE VOICE (non-subject is promoted to topic position). Some linguists have also identified a "middle" voice.

# What is wrong with the following sentences?

1. What he was doing? FAILURE TO INVERT AUXILIARY VERB IN NON-SUBJECT QUESTION
2. Who did eat eat all the pies? INCORRECT APPLICATION OF DO-SUPPORT IN A SUBJECT QUESTION
3. Boy we're having a good time!! FAILURE TO INVERT AUXILIARY IN EXCLAMATIVE
4. He's happy? FAILURE TO INVERT COPULA IN NON-SUBJECT QUESTION
5. Who did he give the book to someone? WH-MOVEMENT WITHOUT DELETION OF MOVED CONSTITUENT
6. You put that bottle of paint down! FAILURE TO OMIT SUBJECT IN IMPERATIVE
7. How many cakes he has eaten? FAILURE TO INVERT AUXILIARY VERB IN NON-SUBJECT QUESTION

# Do the following modal verbs express deontic or epistemic modality?

1. You must be joking! EPISTEMIC
2. Q: Does anyone know a late bar? A: The King George ought to be open. EPISTEMIC
3. You can't have dinner at this establishment unless you are wearing a tie. DEONTIC
4. The train to York shouldn't be long now. EPISTEMIC
5. You'll have to work hard if you want to be successful. DEONTIC

# Are the following sentences active or passive? Use the "hedgehogs" test to find out!

1. She's been really unlucky recently! ACTIVE
2. They've just been badly criticised. PASSIVE
3. The car needs to be mended. PASSIVE
4. I have had enough of your glib comments! ACTIVE
5. By the time we arrive all the food will have been eaten. PASSIVE
6. She's tried, on numerous occasions, to contact her bank manager. ACTIVE
7. Hopefully, we'll be successful in the next round. ACTIVE
8. When we arrived, the house was being demolished. PASSIVE


`r unhide()`
