---
title: "08 - Verbs in the driving seat"
output:
  html_document:
    css: webex.css
    includes:
      after_body: webex.js
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!requireNamespace("webex")) {
  stop("You must have the 'webex' package installed to knit HTML from this template.\n   devtools::install_github(\"dalejbarr/webex\")")
} else {
  library("webex")
}
```

# Identify the thematic relations of the underlined words

1. <u>The boat</u> sank in the rough seas

The boat = `r mcq(c(answer = "Agent", "Experiencer", "Patient", "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

2. <u>Janice</u> despised <u>her cousin</u> for her rampant consumerism

Janice = `r mcq(c("Agent", answer = "Experiencer", "Patient", "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

her cousin = `r mcq(c("Agent", "Experiencer", "Patient", answer = "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

3. <u>The film</u> really disturbed <u>me</u>

The film = `r mcq(c("Agent", "Experiencer", "Patient", answer = "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

me = `r mcq(c("Agent", answer = "Experiencer", "Patient", "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

4. <u>Martin</u> hammered <u>the nail</u> <u>flat</u>

Martin = `r mcq(c(answer = "Agent", "Experiencer", "Patient", "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

the nail = `r mcq(c("Agent", "Experiencer", answer = "Patient", "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

flat = `r mcq(c("Agent", "Experiencer", "Patient", "Theme", "Benefactive", answer = "Attributive", "Locative", "Instrument", "Possessor"))`

5. <u>Anthony</u> made <u>his neighbour</u> <u>a birthday cake</u>

Anthony = `r mcq(c(answer = "Agent", "Experiencer", "Patient", "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

his neighbour = `r mcq(c("Agent", "Experiencer", "Patient", "Theme", answer = "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

a birthday cake = `r mcq(c("Agent", "Experiencer", answer = "Patient", "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

7. <u>Chen</u> made <u>his landlord</u> <u>furious</u>

Chen = `r mcq(c(answer = "Agent", "Experiencer", "Patient", "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))` (NB assumes that action is deliberate. If not deliberate, it is difficult to determine a role)

his landlord = `r mcq(c("Agent", answer = "Experiencer", "Patient", "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

furious = `r mcq(c("Agent", "Experiencer", "Patient", "Theme", "Benefactive", answer = "Attributive", "Locative", "Instrument", "Possessor"))`

8. <u>Rufus</u> owns <u>a villa</u> in the South of France

Rufus = `r mcq(c("Agent", "Experiencer", "Patient", "Theme", "Benefactive", "Attributive", "Locative", "Instrument", answer = "Possessor"))`

a villa = `r mcq(c("Agent", "Experiencer", "Patient", answer = "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

9. <u>Sandra</u> smeared <u>cream</u> <u>on her face</u> 

Sandra = `r mcq(c(answer = "Agent", "Experiencer", "Patient", "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

cream = `r mcq(c("Agent", "Experiencer", answer = "Patient", "Theme", "Benefactive", "Attributive", "Locative", "Instrument", "Possessor"))`

on her face = `r mcq(c("Agent", "Experiencer", "Patient", "Theme", "Benefactive", "Attributive", answer = "Locative", "Instrument", "Possessor"))`





`r hide("Answers")`

# Identify the thematic relations of the underlined words

1. <u>The boat</u> sank in the rough seas

PATIENT: Passes the 'what happened to...' test, e.g. 'What happened to the boat was it sank'

2. <u>Janice</u> despised <u>her cousin</u> for her rampant consumerism

Janice = EXPERIENCER, her cousin = THEME

3. <u>The film</u> really disturbed <u>me</u>

The film = THEME, me = EXPERIENCER.

Note that these two verbs are 'mirror images' of each other. Themes are often paired with experiencers.

4. <u>Martin</u> hammered <u>the nail</u> <u>flat</u>

Martin = AGENT, the nail = PATIENT, flat = ATTRIBUTIVE

5. <u>Anthony</u> made <u>his neighbour</u> <u>a birthday cake</u>

Anthony = AGENT, his neighbour = BENEFACTIVE, a birthday cake = PATIENT

6. <u>Chen</u> made <u>his landlord</u> <u>furious</u>

Chen = AGENT (NB only if he deliberately annoys his landlord! If the action is not deliberate, Chen could be described as a theme), landlord = EXPERIENCER (landlord is highly affected, but it is a PSYCHOLOGICAL effect), furious = ATTRIBUTIVE.

7. <u>Rufus</u> owns <u>a villa</u> in the South of France

Rufus = POSSESSOR, a villa = THEME

8. <u>Sandra</u> smeared <u>cream</u> <u>on her face</u>

Sandra = AGENT, cream = PATIENT, on her face = LOCATIVE.

`r unhide()`

