---
name: "Linguistics Course"  
author: "Nick Riches"  
output:  
  word_document: default
  html_document:  
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
---
# Homework

"Is you is, or is you ain't my Baby?"

This is a quite probably **pastiche** of African American Vernacular English (AAVE). It was originally used in a story by non-African American (Jewish) short story writer Octavus Roy Cohen. Though it is unlikely to be genuine AAVE, it was incoporated by African American songwriter, Louis Jordan into his famous song.

From a linguistic perspective it is interesting because it shows (a) non-standard agreement morphology ("you is"), (b) non-standard form of the negative copula (ain't), (c) movement without deletion (see later).

# Mood, modality and voice

These are all phenomena which can be used to manipulate the proposition expressed by a sentence.

**Mood** and **modality** are devices whereby speakers express their <u>attitude to what they they are saying</u>.

**Voice** is a means of <u>foregrounding (or "topicalising") particular arguments</u>

# Mood

## Types of mood, with examples

In English "moods" are typically aligned with Speech Acts;

1. Declarative Mood for comments (when written, they end in a full-stop/period: ".")

   e.g. "She is late for work", "The cat ate the fish".

2.  Interrogative Mood for questions (when written, they end in a question mark: "?")

   e.g. "Who do you work for?", "Why are you being so mean?"

3.  Imperative Mood for directives (e.g. commands. When written they end in an exclamation mark: "!")

   e.g. "Don't do that!", "Go away!

4.  Exclamative Mood (when written, they also end in an explanation mark: "!")

   e.g. "What a terrible film!", "Boy was it awful!"

## Mood in other languages

Some languages have yet further moods, e.g. Romance languages have a "subjunctive" mood which is used to refer to events which are hypothetical.

## Declarative Mood

In most discourses, most sentences will be in the declarative mood. This exhibits the canonical word order of a language. In English this is Subject + Verb + Complement of the verb (optional)

1. She $_{Subj.}$ is $_{Vb.}$ late for work $_{Comp. (Cs)}$
2. The cat $_{Subj.}$ ate $_{Vb.}$ the fish $_{Comp. (Od)}$

## Interrogative Mood

Interrogatives can either use "wh-words" (sometimes called "open questions", "wh-questions"), e.g.

1. **Who** did you see?

... or they can be closed questions, e.g.

2. Did you like the book I gave you?

There are two main processes:

1. Wh-movement
2. Inversion of auxiliary or copula

These processes are only found in questions where the wh-word does **not refer to the subject** (these are called non-subject questions)

Here are some examples:

1. What is he _ doing? (Non-subject question demonstrating wh-movement and auxiliary inversion)
2. Where is he _ ? (Non-subject question demonstrating wh-movement and copula inversion)
3. Who ate the chips? (Subject question with no apparent auxiliary inversion)

"Is you is, or is you ain't my baby" is unusual because it contains movement of the copula/auxiliary to the front of the sentence, but the moved element is not deleted in its place of origin.

## Exclamative mood

Some exclamatives look very similar to interrogatives:

1. What a nice guy! (use of "wh" words)
2. Boy was it awful! (inversion of copula)
3. Gee was I laughing a lot! (inversion of auxiliary)

It has been argued that exclamative forms develop from interrogative forms (Goldberg, A. E. (2006). *Constructions at Work: The Nature of Generalization in Language*. Oxford, UK: Oxford University Press. CHAPTER 8). They are also developmentally prior, so could exclamatives be used to teach complicated aspects of question formation (e.g. auxiliary inversion), and could they then form the basis of an intervention for interrogative forms?

## Imperative mood

For the interrogative mood, the subject is omitted, and the infinitive form of the verb is used:

1. (You) **be** quiet in the library!
2. (You) **go** slowly!
3. (You) **don't drive** so fast!

Note that the negative form is unusual. Typically, infinitives use the particle "not" in the negative, e.g.

1. He decided **not to go** to the party

# Modality

## The basics

On a SEMANTIC level "modality" refers to the concepts of OBLIGATION (DEONTIC MODALITY) or LIKELIHOOD (EPISTEMIC MODALITY)

On a SYNTACTIC level "modality" is typically expressed using **modal auxiliary verbs**, e.g. "must", "should".

Here are some examples

1. You **must** arrive on time. (DEONTIC MODALITY)
2. Jack **must** be running late (EPISTEMIC MODALITY)
3. You **shouldn't** smoke. (DEONTIC MODALITY)
4. He **shouldn't** be long now (EPISTEMIC MODALITY)

Note that modal verbs "double-up" and are able to express both DEONTIC and EPISTEMIC modality depending on the context.

Modal verbs have 4 important grammatical properties

1. They don't inflect for tense, e.g. * *She **musted** arrive on time*
2. They don't inflect for agreement, e.g. * *She **musts** arrive on time*
3. They are followed by the inifinitive form (without "to"), e.g. *She must <u>arrive</u> on time*.
4. They invert to make questions, e.g. *Should I _ bring a packed lunch?*

## Getting tricky

### "Permission" modals

All model verbs are dual-purpose, i.e. able to express either DEONTIC or EPISTEMIC modality in different situations (see above examples). Some modal verbs appear to seek permission, e.g.

1. You may not have some more (GIVING PERMISSION)
2. **May** I have some more please (SEEKING PERMISSION)

These "permission" type modal verbs are actually "disguised" deontic modal verbs, e.g.

You may have some more —> It's NOT the case that you must NOT have some more

### "Will"

"Will" is often described as a modal verb because it exhibits all the syntactic characterstics of modal verbs, e.g. no inflection for tense/agreement, followed by infinitive and inverted to make a question.

However, "will" very rarely expresses a modal meaning (e.g. *You will not smoke in here!* = You can't smoke in here). In contexts where it does not have a modeal meaning it should not be categorised as a modal verb (though many grammar texts actually do this!).

### "Can"

Can is often used as a modal verb, e.g.

1. You **can't** smoke here (DEONTIC MODALITY)
2. You **can't** be serious (EPISTEMIC MODALITY)

However, when used to expressed ability, it is NOT a modal verb, as it does not have a modal meaning,

e.g.

1. I can't do this homework (ABILITY = NON-MODAL MEANING).

### Semi-modals

These are verbs which express modal concepts (OBLIGATION), but do not exhibit the typical grammatical properties of modal verbs, e.g. *need to*, *have to*;

1. They inflect for tense, e.g. *He **had to/needed to** work harder*
2. They inflect for agreement, e.g. *He **has to/needs to** work harder* 
3. Questions use do-support instead of inverstion, e.g. *Do I **have to/need to** work harder?*

Because they inflect for tense, they are very useful for expressing modal concepts in the past.

# Voice

## Active versus passive voices - the basics

In English (and many languages), the topic of the sentence (the thing it is "about") is often placed in subject position:

1. Have you watched "**The Walking Dead**"?
2. **It**'s one of my favourite series.
3. **It**'s about a group of surviviors fighting zombies in an apocalyptic wasteland.
4. **It**'s really quite gripping.
5. **It**'s made by an American Channel called AMC
6. **The pilot episode** was directed by Frank Darabont, who directed the Shawshank Redemption.

Notice that 5. and 6. have a slightly different structure. These are examples of the Passive.

The structure is SUBJECT + AUX. BE (or sometimes "get") + PAST PARTICIPLE OF VERB + OPTIONAL "BY-PHRASE"

The passive is used to **topicalise a non-subject constituent.** The process of passivisation turns a non-subject into a subject.

Both **direct** and **indirect** objects can be passivised:

1. Food was given _ to all the refugees (by the aid workers)

   Passive voice. Movement of Od to Subject (Topic) position

2. The refugees were given _ food (by the aid workers)

   Passive voice. Movement of Oi to Subject (Topic) position.

But Subject and Object Complements cannot be passivised

1. She seems nice -> * Nice is seemed by her
2. They elected him captain of the team -> He was elected captain of the team (passivisation of Od) -> * Captain of the team was elected him by them (failed passivisation of Co).

If you wish to find out whether a sentence is passive you can use the "Hedgehog" test. Just insert the phrase "by hedgehogs" and if the sentence remains grammatical, then it is a passive:

1. Food was given to all the refugees **by hedgehogs**.
2. All of the food had been eaten **by hedgehogs**
3. *He's been working for ten hours **by hedgehogs**

## Other voices

Other voicing systems have been identified. E.g. you may come across the "middle" voice at some time in your reading.

However, we are not going to be focusing on these...

## The passive gets a bad press!

Use of the passive is often criticised, and many style manuals, e.g. Strunk and White, "The Elements of Style", warn against it.

One possible reason is that the passive can be used to hide the "agent", e.g.

1. TEENAGER: Mum, I invited a few friends around, and unfortunately <u>the TV was broken</u>.

It is therefore seen as a "dishonest" construction. Also, in critical discourse studies, which looks at how language is used to persuade and promote idology, the passive is also described as a dishonest construction because it hides agency, e.g.

1. The miners were arrested (by Police)

However, as the above example shows (Walking Dead example), the passive is extremely useful for topic maintenance, which is important for maintaining a coherent discourse. It is perfectly okay to use the passive in contexts where it is appropriate.

## The passive in language-impaired populations

Individuals with developmental/acquired language impairments have great difficulties producing the passive (Van der Lely, H. K. J. (1996). Specifically language impaired and normally developing children: Verbal passive vs adjectival passive sentence interpretation. *Lingua*, *98*, 243–272.)

You will find that many assessments of both production and comprehension (e.g. CELF recalling sentences, or TROG comprehension task) employ the passive.

# Homework

The following sentence is actually grammatical

1. The horse raced past the barn fell

Can you create a discourse context where the sentence makes sense.

# Bibliography

Friedmann, N., Novogrodsky, R. (2011). Which questions are most difficult to understand?: The comprehension of Wh questions in three subtypes of SLI. Lingua, 121, 367ˆa382.

Jyotishi, M., Fein, D., & Naigles, L. (2017). Investigating the Grammatical and Pragmatic Origins of Wh-Questions in Children with Autism Spectrum Disorders. Frontiers in Psychology, 8. https://doi.org/10.3389/fpsyg.2017.00319

Papafragou, A. (1998). The Acquisition of Modality: Implications for Theories of Semantic Representation. Mind & Language, 13(3), 370-399. https://doi.org/10.1111/1468-0017.00082

van der Lely, H. K. J. (1996). Specifically language impaired and normally developing children: Verbal passive vs adjectival passive sentence interpretation. Lingua, 98, 243-272.

van der Lely, H. K. J., & Battel, J. (2003). Wh-movement in children with grammatical SLI: A test of the RDDR hypothesis. Language, 79, 153-181.

