---
title: "01 - Introduction"
output:
  html_document:
    css: webex.css
    includes:
      after_body: webex.js
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!requireNamespace("webex")) {
  stop("You must have the 'webex' package installed to knit HTML from this template.\n   devtools::install_github(\"dalejbarr/webex\")")
} else {
  library("webex")
}
```

# Concept-checking

Fill the blanks:

S`r fitb("yntax", ignore_case = TRUE, width = "15")` is the study of language structure. S`r fitb("emantics", ignore_case = TRUE, width = "15")` is the study of linguistic meaning. Pr`r fitb("agmatics", ignore_case = TRUE, width = "15")` is the study of language in context. Ph`r fitb("onology", ignore_case = TRUE, width = "15")` is the study of the sound system of language.

D`r fitb("escriptive", ignore_case = TRUE, width = "15")` grammar describes the utterances people produce. M`r fitb("escriptive", ignore_case = TRUE)` describes the underlying system of rules in our minds which are used to derive sentences.  P`r fitb("rescriptive", ignore_case = TRUE)` grammars describe how we should / shouldn't use language.

Hyp`r fitb("ercorrection", ignore_case = TRUE)` happens when there is a conflict between prescriptive grammars and our mental grammar, and we prioritise our prescriptive grammars.

According to Weinreich, a language is  d`r fitb("ialect", ignore_case = TRUE)` with an  a`r fitb("rmy", ignore_case = TRUE)` and a  n`r fitb("avy", ignore_case = TRUE)`

# Varieties of English

For the following sentences from non-standard varieties of English (a) how would you say them in standard English (b) which non-standard variety do they come from?
 
1. He couldn't wouldn't have worked.

DIALECT = `r mcq(c("Indian English", "Bengali English", answer = "Geordie English", "Yorkshire English", "Liverpool English", "American English", "Southern US English", "African American Vernacular English"))`

`r hide("Show answer")`

Standard English - He wasn’t able to work. This example is from _Geordie English_. Speakers make combinations of modal auxiliary verbs which are not permissible in standard English (Modal verbs are covered in Lecture 9 this semester)

`r unhide()` <br>

2. She was having many dresses

DIALECT = `r mcq(c(answer = "Indian English", "Bengali English", "Geordie English", "Yorkshire English", "Liverpool English", "American English", "Southern US English", "African American Vernacular English"))`

`r hide("Show answer")`

Standard English - _She had many dresses_. This example is from Indian English. Progressive aspect (shown by -ing) is used with the verb have. Whereas in English have cannot take progressive aspect, in Indian English it can. Aspect will be covered later in the course.

`r unhide()` <br>

3. I like that you're unpredictable

DIALECT = `r mcq(c("Indian English", "Bengali English", "Geordie English", "Yorkshire English", "Liverpool English", answer = "American English", "Southern US English", "African American Vernacular English"))`

`r hide("Show answer")`

In UK standard English we use like and then a noun, e.g. I like the fact that you’re unpredictable, or maybe I like it that you’re unpredictable. However, the above structure, where we use like plus a "clause" (a mini-sentence introduced by that) is becoming more common in standard English. To me it sounds a bit weird, but to you it may sound fairly normal. This expression is extremely common in American English and has probably "crossed the pond"

`r unhide()` <br>


4. He divn't gan tiv a college ti di that, man!

DIALECT = `r mcq(c("Indian English", "Bengali English", answer = "Geordie English", "Yorkshire English", "Liverpool English", "American English", "Southern US English", "African American Vernacular English"))`

`r hide("Show answer")`

Standard English - He didn’t go to college to do that. This example is from _Geordie English / Northumberland English_. There are many local variations here; didn’t → divn’t, go → gan, tiv → to, do → di.

`r unhide()` <br>

5. He went out to lunch and had one sandwich

DIALECT = `r mcq(c(answer = "Indian English", "Bengali English", "Geordie English", "Yorkshire English", "Liverpool English", "American English", "Southern US English", "African American Vernacular English"))`

`r hide("Show answer")`

Standard English - _He went out to lunch and had a sandwich_. The example is from _Indian English_. Determiner _One_ is used instead of a. This is due to transfer from Hindi where _one_ and _a_ are the same word

`r unhide()` <br>

6. I told thee that it were right good!

DIALECT = `r mcq(c("Indian English", "Bengali English", "Geordie English", answer = "Yorkshire English", "Liverpool English", "American English", "Southern US English", "African American Vernacular English"))`

`r hide("Show answer")`

Standard English - I told you that it was really good. This is from Yorkshire English. Thee is used for second person singular pronoun. Were is used as the third person singular past tense form of the verb to be. Right is used as an intensifier (a type of adverb).

`r unhide()` <br>

7. She been married a long time.

DIALECT = `r mcq(c("Indian English", "Bengali English", "Geordie English","Yorkshire English", "Liverpool English", "American English", "Southern US English", answer =  "African American Vernacular English"))`

`r hide("Show answer")`

Standard English - _She has been married for a long time_. The example is from _African American Vernacular English_. The use of _been_ has a very specific meaning, to show that the event has lasted for a long time. So while conservative commentators in the US have argued that AAVE is a "corrupted" form of English, this example shows us that so-called "incorrect" sentences actually have very sophisticated meanings. It is actually more sophisticated than Standard English, which does not make this distinction.

`r unhide()` <br>

8. What are youse doing?

DIALECT = `r mcq(c("Indian English", "Bengali English", "Geordie English","Yorkshire English", answer = "Liverpool English", "American English", "Southern US English", "African American Vernacular English"))`

`r hide("Show answer")`

Standard English - What are you doing? Youse is used as a plural form in a number of English dialects including Liverpool English

`r unhide()` <br>

9. What are y'all doing?

DIALECT = `r mcq(c("Indian English", "Bengali English", "Geordie English","Yorkshire English", "Liverpool English", "American English", answer = "Southern US English", "African American Vernacular English"))`

`r hide("Show answer")`

Standard English - What are you doing? _Y’all_ is used as a plural form in a number of Southern US dialects

`r unhide()` <br>

10. He's a good block, innit?

DIALECT = `r mcq(c("Indian English", answer = "Bengali English", "Geordie English","Yorkshire English", "Liverpool English", "American English", "Southern US English", "African American Vernacular English"))`

`r hide("Show answer")`

Standard English - He’s a good bloke, isn’t he? _Innit_ is used as a tag question in central London and other urban areas in the UK. It may have originated from Bengali English.

`r unhide()` <br>


