---
title: "poo | subtitle"
subtitle: "asdfsdaf"
# author: "Nick Riches"
# date: "31/07/2018"
output:
    ioslides_presentation:
  # html_document:
  #     number_sections: yes
  #     toc: yes
  #     toc_float:
  #       collapsed: yes
  #       toc_depth: 2
 # ioslides_presentation: default
---


<script>

    doctype = "slides_student"; // or "slides_student" or "slides_master"
    
</script>

<style>

    h2 {
        color: #000066;
    }
    
    body p {
      color: #000000;
    }

    div {
      color: #000000;
    }

    slides > slide {
      font-family: "Times New Roman", Times, serif;
    }

</style>


# Introduction - real language data



# What is linguistics?

## Scope of linguistics

Theoretical linguistics - What does our knowledge of language look like?

Applied linguistics - How do we use language?

Psycholinguistics - How is language stored / processed in the mind?

Sociolinguistics - How and why does language use vary according to social group?

<div class = "handout_only">

text for handout only

</div>


## Subdisciplines of theoretical linguistics

### Semantics

---

Semantics = linguistic meaning at _word_ or _sentence_ level

---



# Why is it relevant to SLT practice?

## Diagnosis

Him go there

## Identifying therapy targets



## Finding new ways to treat language impairments



# A closer look at grammar

##

## Levels of description

## Structural hierarchies







<script>

    if(doctype == "slides_student"){  
    var myClasses = document.querySelectorAll('.handout_only'),
        i = 0,
        l = myClasses.length;

    for (i; i < l; i++) {
        myClasses[i].style.display = 'none';
      }
    }
    
        if(doctype == "handout"){  
    var myClasses = document.querySelectorAll('.slides_only'),
        i = 0,
        l = myClasses.length;

    for (i; i < l; i++) {
        myClasses[i].style.display = 'none';
      }
    }
    
</script>
