---
name: "Linguistics Course - Resources"  
author: "Nick Riches"  
output:  
  html_document:  
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
---

# Introduction to Linguistic Theory

__READINGS:__

Borjars & Burridge, Chapter 1

Steven Pinker’s The Language Instinct, Chapter 12, The Language Mavens This is a brilliant demolition of prescriptive grammars.

Pullum, G. (1999) [African American Vernacular English is not standard English with mistakes](www.stanford.edu/~zwicky/aave-is-not-se-with-mistakes.pdf). In R. S. Wheeler (Ed.), The workings of language From prescriptions to perspectives (pp. 39-58). Westport, CT Praeger.

In addition you can read [this chapter](old chapters/1_introduction_reduced.pdf) from a book I wrote to accompany last year's course. I will no longer be using this book, as the course structure has changed quite a lot, but when certain chapters are relevant I will provide links to them.

__OTHER RESOURCES:__

[Gretchen McCulloch podcast on 'Kids these days aren’t ruining language'](https://lingthusiasm.com/post/159796192161/lingthusiasm-episode-7-kids-these-days-arent)

[Article on the use of double negatives in the Economist](https://www.economist.com/prospero/2018/07/18/a-grammatical-analysis-of-donald-trumps-double-negatives)

[Good blog on African American Vernacular English](http://www.languagejones.com/blog-1/2014/6/8/what-is-aave)

[Wikipedia article on Bill Cosby's famous speech criticising AAV English](https://en.wikipedia.org/wiki/Pound_Cake_speech)

[Article in the Daily Mail reporting head teacher who bans local slang](http://www.dailymail.co.uk/news/article-3177901/Struggling-school-turns-round-fortune-banning-slang-words-innit-ain-t-coz-woz.html), [and another...](http://www.dailymail.co.uk/news/article-3565133/Shut-Geezer-runs-Essex-school-like-pupils-stop-speaking-Towie.html) and [a response by Rob Drummond (Manchester University) in the academic magazine 'the Conversation'](https://theconversation.com/slang-shouldnt-be-banned-it-should-be-celebrated-innit-58672) (P.S. the Daily Mail articles are clearly nonsense!!)

[A further article on a school which tries to ban the local Black Country  dialect](https://www.theguardian.com/education/2013/nov/14/black-country-headteacher-banning-dialect)

[And another school in London](https://www.theguardian.com/uk-news/2013/oct/15/london-school-bans-pupils-slang-innit) which has attempted to ban certain linguistic features from the local dialect.

[Here are some poor Bostonians trying to shed their local accent](https://www.youtube.com/watch?feature=player_embedded&v=ketrhWr58wA)

[A good article on hyper-correction](https://www.thoughtco.com/hypercorrection-grammar-and-pronunciation-1690937)

[Great Mitchell and Webb sketch which riffs on a prescriptive approach to language (be warned, cartoonish violence involving blood)](https://www.youtube.com/watch?v=j4hvh5e8-nw)

[Steven Pinker on prescriptive grammar](http://www.youtube.com/watch?v=Q-B_ONJIEcE&t=5m28s)

# Word Classes

__READINGS:__

Borjars & Burridge, Chapter 3

McAllister & Miller, Chapter 5

Here is a [link](old chapters/2_building_blocks_reduced.pdf) the relevant chapter in the old handbook

__OTHER RESOURCES:__

[Gretchen McCulloch podcast on 'Getting into, up, for, and down with prepositions') ](https://lingthusiasm.com/post/167572233831/lingthusiasm-episode-14-getting-into-up-for-and)

[English has a new preposition!](https://www.theatlantic.com/technology/archive/2013/11/english-has-a-new-preposition-because-internet/281601/)

[A YouTube video on lexical gaps](https://www.youtube.com/watch?v=Zw5WctmULD8)

[Cool cartoon on the arbitrariness of words](images/names are arbitrary t-rex.png) (remember, arbitrariness is a key characteristics of symbols)

# Lexical representation

__READINGS__

Cruse, A. (2010). Meaning in Language, Chapter 4 on the definition of a word, and Chapter 5 on Homonomy and Polysemy

McAllister & Miller, Chapters 2 and 3. 
 
__OTHER RESOURCES__

[YouTube lecture on Polysemy (given by Martin Hilpert)](https://www.youtube.com/watch?v=dEWTCzK_hUU&t=19s)

# Words versus morphemes

__READINGS__

Borjars & Burridge, Chapter 2 (sections 2.1 and 2.2)

McAllister & Miller, Chapter 6

__OTHER RESOURCES__

[Gretchen McCulloch podcast on 'Learning parts of words: morphemes and the wug test'](https://lingthusiasm.com/post/169866479416/lingthusiasm-episode-16-learning-parts-of-words)

# Morphological representation / processing

__READINGS__

[Pinker, S., & Ullman, M. T. (2002). The past and future of the past tense debate. Trends in Cognitive Sciences, 6(11), 456–463](https://www.sciencedirect.com/science/article/pii/S1364661302019903)

After the initial paper there are responses by Joanisse and Seidenberg. It's well worth reading all of them.

Dabrowska, E. (2004). Language, mind and brain: some psychological and neurological constraints on theories of grammar. Edinburgh University Press.  (Chap 8, especially 116 – 125. The rest of the chapter is difficult but very interesting)

# Phrases

__READINGS:__

Borjars & Burridge, Chapter 2 (2.3 onwards)

McAllister & Miller, Chapter 7 (up to 7.4)

__OTHER RESOURCES__ 

[Gretchen McCulloch podcast on 'Constituency'](https://lingthusiasm.com/post/161859273886/lingthusiasm-episode-9-the-bridge-between-words)

# Functions

__READINGS:__

Borjars & Burridge, Chapter 4

[Chapter from old Linguistics handbook on Case and Agreement](old chapters/2_tracking_relationships.pdf)


# Verbs in the driving seat

__READINGS:__

Saeed, Sections 6.1 - 6.6

Cruse, Part 3 Section 14

Carnie, Chapter 7

Bryan, A.(1997). Colourful semantics: Thematic role therapy.
In S. Chiat, J. Law, & J. Marshall (Eds.),_ Language
disorders in children and adults: Psycholinguistic
approaches to therapy_ (pp. 143-161). London: Whurr.

[Chapter from old Linguistics handbook on Argument Structure](old chapters/argument_structure_chapter.pdf)

[Gretchen McCulloch Podcast on how the sentence is organised around the verb](https://lingthusiasm.com/post/182969748701/lingthusiasm-episode-29-the-verb-is-the-coat-rack)

# Complementation versus modification

 _Carnie, A. (2002). Syntax a generative introduction. Blackwell Pub._, Section 6.3. 
 
Here is a useful online resource:

[UCL Internet Grammar](http://www.ucl.ac.uk/internet-grammar/phfunc/compare.htm)

# Garrett Model of sentence production

Harley, T. A. [The Psychology of Language](https://libsearch.ncl.ac.uk/primo-explore/search?query=any,contains,harley%20psycholinguistics&tab=default_tab&search_scope=NotPC&sortby=date&vid=NEWUI&facet=frbrgroupid,include,1443333280&lang=en_US&offset=0). Hove: Psychology Press. Section E on Language Production

Gleason, J. B. & Ratner, N. B. (1998). [Psycholinguistics](https://libsearch.ncl.ac.uk/primo-explore/search?query=any,contains,gleason%20psycholinguistics&tab=default_tab&search_scope=NotPC&vid=NEWUI&lang=en_US&offset=0) (2nd edition). Chapter 7

Sedivy, [Psycholinguistics](https://libsearch.ncl.ac.uk/primo-explore/fulldisplay?docid=NCL_ALMA21113350300002411&context=L&vid=NEWUI&lang=en_US&search_scope=NotPC&adaptor=Local%20Search%20Engine&tab=default_tab&query=any,contains,sedivy&sortby=rank&offset=0), Chapter 9

# Verbs in the passenger seat

Here is a very accessible [YouTube video by Martin Hilpert](https://www.youtube.com/watch?v=9DllnszLuM0) on Construction Grammar, and [this YouTube video](https://www.youtube.com/watch?v=GN1MrP396Y4) focuses on Construction Grammar approaches to argument structure.

A reasonably simple written introduction to "Construction Grammar" is provided by Tomasello, M. (1998). [The Return of Constructions](https://www.cambridge.org/core/journals/journal-of-child-language/article/return-of-constructions/7E8A1AA5FF8DA4385E991B03B1AA4A09). Journal of Child Language, 25, 431–442.

A more complex and thorough treatment is provided in
_Goldberg, A. E. (1995). Constructions a Construction Grammar approach to argument structure. University of Chicago Press._ is a slightly advanced book on the topic of construction grammar.

# The semantics of events

Saeed, Section 5.2

Also you can look at [the relevant chapter from the old linguistics course](old chapters/9_the_semantics_of_events.pdf)

# The Syntax of Events

Borjars & Burridge, Chapter 6

# Hierarchical Structure

[Steven Pinker on the Argument from the Poverty of the Stimulus](http://www.youtube.com/watch?v=Q-B_ONJIEcE&t=27m0s)

Also have a look at Carnie's "Syntax: a generative introduction"

# Dependent clauses I - adverbial clauses

Borjars & Burridge, Chapter 8

McAllister & Miller, Chapter 9

[Interesting article, by Laura de Ruiter and colleagues, on the processing of adverbial clauses by children](https://www.sciencedirect.com/science/article/pii/S0010027717302780)

# Dependent clauses II - Other types

Borjars & Burridge, Chapter 8 (as before)

McAllister & Miller, Chapter 9 (as before)

[Interesting article, by Kidd and colleagues, on how children acquire senntences with dependent clauses in direct object position](https://www.sciencedirect.com/science/article/pii/S0885201406000256)

# Mood, modality and voice

McAllister & Miller, Chapter 8

Saeed, Chapter 5.3

# What's the use of complex syntax?

Nippold, M. A., Mansfield, T. C., Billow, J. L., & Tomblin, J. B. (2008). [Expository discourse in adolescents with language impairments: Examining syntactic development](https://ajslp-pubs-asha-org.libproxy.ncl.ac.uk/doi/full/10.1044/1058-0360%282008/07-0049%29?casa_token=k5NcsSONPoQAAAAA:vArKP7-jo2dCPu-6jQjRSj-pmtNPerUXPGjjK_zRS_-DUm-j4PrClNI19OVZkBpG30NmFsQ_O39uMg). American Journal of Speech-Language Pathology, 17(4), 356.

# Sentence Comprehension I

Trueswell, J. C., Tanenhaus, M. K., & Kello, C. (1993). [Verb-specific constraints in sentence processing: Separating effects of lexical preference from garden-paths](https://ovidsp-dc1-ovid-com.libproxy.ncl.ac.uk/sp-3.33.0b/ovidweb.cgi?WebLinkFrameset=1&S=DBBNFPIFIMACKCHLKPDKFHINHHMKAA00&returnUrl=ovidweb.cgi%3f%26TOC%3djb.search.27%257c3%257c50%26FORMAT%3dtoc%26FIELDS%3dTOC%26S%3dDBBNFPIFIMACKCHLKPDKFHINHHMKAA00&directlink=https%3a%2f%2fovidsp.dc1.ovid.com%2fovftpdfs%2fFPACKPINFHHLIM00%2ffs046%2fovft%2flive%2fgv025%2f00004786%2f00004786-199305000-00003.pdf&filename=Verb-Specific+Constraints+in+Sentence+Processing%3a+Separating+Effects+of+Lexical+Preference+From+Garden-Paths.&PDFIdLinkField=%2ffs046%2fovft%2flive%2fgv025%2f00004786%2f00004786-199305000-00003&link_from=jb.search.27%7c3&pdf_key=B&pdf_index=jb.search.27&D=ovft). JOURNAL OF EXPERIMENTAL PSYCHOLOGY LEARNING MEMORY AND COGNITION, 19, 528-528.

# Sentence Comprehension II


Kidd, E., Brandt, S., Lieven, E., & Tomasello, M. (2007). [Object relatives made easy: A cross-linguistic comparison of the constraints influencing young children’s processing of relative clauses](https://www.google.com/search?q=object+relatives+made+easy&oq=object+relatives+made+easy&aqs=chrome..69i57j33l4.6156j0j7&sourceid=chrome&ie=UTF-8). Language and Cognitive Processes, 22(6),
860–897.

# Formulaicity

Wray, A., & Perkins, M. R. (2004). [The functions of formulaic language: an integrated model](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.558.6248&rep=rep1&type=pdf). Language & Communication, 20(1),1-28.

# Linguistics in the clinic

Ebbels, S. (2007). [Teaching grammar to school-aged children with specific language impairment using shape coding](https://journals-sagepub-com.libproxy.ncl.ac.uk/doi/10.1191/0265659007072143). Child Language Teaching & Therapy, 23(1), 67.

[Parleé Podcast on multi-modal approaches to intervention](http://www.theparlepodcast.com/the-parleacute-podcast/episode-10-tips-and-tricks-on-how-to-use-a-multimodal-approach-when-working-with-children-who-have-dld-featuring-shaun-ziegenfusz.html#)

<!-- https://www.youtube.com/watch?v=GN1MrP396Y4 -->

<!-- [Article on how the passive voice is used to report conflict](https://www.theguardian.com/commentisfree/2018/may/16/israel-palestine-us-news-headlines-mysterious-deaths?CMP=Share_iOSApp_Other), but are the supposed examples of the 'passive' really the passive? -->



<!-- [Steven Pinker on the Argument from the Poverty of the Stimulus](http://www.youtube.com/watch?v=Q-B_ONJIEcE&t=27m0s) -->



<!-- THE BIG BAN THEORY https://www.youtube.com/watch?v=NiylEdcIZ2Q -->
